name: Build & Deploy (tag)

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: django-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yc CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
      - name: Configure yc SA key (from base64)
        run: |
          echo "${{ secrets.YC_SA_KEY_JSON_B64 }}" | base64 -d > sa-key.json
          yc config set service-account-key sa-key.json
          yc config set token ""
      - name: Docker login to YCR (IAM)
        run: |
          TOKEN=$(yc iam create-token)
          echo "$TOKEN" | docker login cr.yandex -u iam --password-stdin
      - name: Build & Push
        env:
          TAG: ${{ github.ref_name }}
        run: |
          IMAGE="cr.yandex/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${TAG}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

  deploy:
    needs: build
    runs-on: [self-hosted, linux, x64, srv]
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl & helm & yc
        run: |
          which kubectl || (sudo apt-get update && sudo apt-get install -y kubectl)
          which helm || (curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash)
          which yc || (curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash && echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH)

      # Подготовим kubeconfig: берём локальный, иначе секрет; кладём в рабочую папку и используем --kubeconfig
      - name: Prepare kubeconfig (persist + sanity check)
        run: |
          set -e
          if [ -f "/home/ubuntu/kubeconfig" ]; then
            SRC="/home/ubuntu/kubeconfig"
            echo "Using local kubeconfig: $SRC"
          elif [ -f "$HOME/kubeconfig" ]; then
            SRC="$HOME/kubeconfig"
            echo "Using local kubeconfig: $SRC"
          else
            echo "Local kubeconfig not found, decoding secret..."
            echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > kubeconfig
            SRC="$PWD/kubeconfig"
          fi
          cp -f "$SRC" "$PWD/kubeconfig"
          chmod 600 "$PWD/kubeconfig"
          # делаем доступным для следующих шагов
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
          # sanity-check ИМЕННО с явным --kubeconfig
          kubectl --kubeconfig "$PWD/kubeconfig" config view >/dev/null
          kubectl --kubeconfig "$PWD/kubeconfig" get nodes

      - name: Configure yc SA key (from base64)
        run: |
          if [ -f "/home/ubuntu/sa-key.json" ]; then
            yc config set service-account-key "/home/ubuntu/sa-key.json"
          elif [ -f "$HOME/sa-key.json" ]; then
            yc config set service-account-key "$HOME/sa-key.json"
          else
            echo "${{ secrets.YC_SA_KEY_JSON_B64 }}" | base64 -d > sa-key.json
            yc config set service-account-key sa-key.json
          fi
          yc config set token ""

      - name: Ensure namespace
        run: |
          kubectl --kubeconfig "$KUBECONFIG" create ns "${{ secrets.KUBE_NAMESPACE }}" \
            --dry-run=client -o yaml | kubectl --kubeconfig "$KUBECONFIG" apply -f -

      - name: Ensure imagePullSecret ycr-pull
        run: |
          TOKEN=$(yc iam create-token)
          kubectl --kubeconfig "$KUBECONFIG" -n "${{ secrets.KUBE_NAMESPACE }}" delete secret ycr-pull --ignore-not-found
          kubectl --kubeconfig "$KUBECONFIG" -n "${{ secrets.KUBE_NAMESPACE }}" create secret docker-registry ycr-pull \
            --docker-server=cr.yandex \
            --docker-username=iam \
            --docker-password="$TOKEN" \
            --docker-email=none@example.com

      - name: Helm upgrade/install
        env:
          TAG: ${{ github.ref_name }}
        run: |
          helm --kubeconfig "$KUBECONFIG" upgrade --install django ./helm/django-postgres \
            --namespace "${{ secrets.KUBE_NAMESPACE }}" \
            --set image.registry=cr.yandex \
            --set image.repo="${{ secrets.REGISTRY_ID }}/django-app" \
            --set image.tag="${TAG}" \
            --set image.imagePullSecrets[0]=ycr-pull
